package edu.msoe.arneyhLab2

public class CourseDatabase {
    companion object {
        private val courseCreditMap = mapOf(

            // Actuarial Science
            "ACS 1010 - Introduction to Actuarial Science" to "2",
            "ACS 2740 - Risk Management and Insurance" to "3",
            "ACS 3410 - Linear Regression and Time Series" to "3",
            "ACS 3420 - Linear Models and Predictive Analytics" to "3",
            "ACS 3530 - Fundamentals of Actuarial Mathematics I" to "3",
            "ACS 3540 - Fundamentals of Actuarial Mathematics II" to "3",
            "ACS 3740 - Introduction to Asset Pricing" to "3",
            "ACS 4410 - Advanced Predictive Analytics" to "3",
            "ACS 4530 - Actuarial Life Contingency Models" to "3",
            "ACS 4630 - Actuarial Probability Models I" to "3",
            "ACS 4640 - Actuarial Probability Models II" to "3",
            "ACS 4740 - Quantitative Risk Management" to "3",
            "ACS 4901 - Actuarial Science Senior Capstone Project" to "3",

            // Air Force
            "AIR 3131 - Leading People and Effective Communication I" to "3",
            "AIR 3132 - Leading People and Effective Communication II" to "3",
            "AIR 4141 - National Security Affairs/Preparation for Active Duty I" to "3",
            "AIR 4142 - National Security Affairs/Preparation for Active Duty II" to "3",
            "AIR 3131 - Leading People and Effective Communication I" to "3",
            "AIR 3132 - Leading People and Effective Communication II" to "3",
            "AIR 4141 - National Security Affairs/Preparation for Active Duty I" to "3",
            "AIR 4142 - National Security Affairs/Preparation for Active Duty II" to "3",

            // Anthropology
            "ANT 1001 - Cultural Anthropology" to "3",
            "ANT 2010 - Culture and Health in Central America" to "3",
            "ANT 2012 - Urban Agriculture: Past, Present, Future" to "3",
            "ANT 2020 - Native American Culture" to "3",

            // Architectural Engineering
            "ARE 2111 - Fundamentals of Electricity and Circuits" to "3",
            "ARE 2851 - Architectural Graphics" to "2",
            "ARE 2852 - Building Information Modeling" to "2",
            "ARE 3101 - Principles of Electrical Engineering for Buildings" to "3",
            "ARE 3121 - Design of Communication and Life Safety Systems" to "3",
            "ARE 3151 - Design of Lighting Systems" to "3",
            "ARE 3161 - Design of Power Systems" to "3",
            "ARE 3401 - Principles of Mechanical Engineering for Buildings" to "3",
            "ARE 3441 - Design of Fire Protection and Life Safety Systems" to "3",
            "ARE 3451 - Design of Mechanical Systems" to "3",
            "ARE 3461 - Design of Plumbing Systems" to "3",
            "ARE 3821 - Architectural History" to "3",
            "ARE 4321 - Soil Mechanics and Foundations" to "3",
            "ARE 4901 - Architectural Engineering Capstone I" to "4",
            "ARE 4902 - Architectural Engineering Capstone II" to "4",

            // Army
            "ARM 1001 - Military Physical Training Laboratory 1" to "1",
            "ARM 1002 - Military Physical Training Laboratory 2" to "1",
            "ARM 1100 - Foundations of Officership" to "1",
            "ARM 1200 - Basic Leadership" to "1",
            "ARM 1800 - American Crucible: The Military and the Development of the United States" to "3",
            "ARM 2001 - Military Physical Training Laboratory 3" to "1",
            "ARM 2002 - Military Physical Training Laboratory 4" to "1",
            "ARM 2100 - Individual Leadership Studies" to "1",
            "ARM 2100 - Individual Leadership Studies" to "2",
            "ARM 2200 - Leadership and Teamwork" to "2",
            "ARM 3001 - Military Physical Training Laboratory 5" to "1",
            "ARM 3002 - Military Physical Training Laboratory 6" to "1",
            "ARM 3100 - Leadership and Problem Solving" to "2",
            "ARM 3101 - Applied Leadership Laboratory I" to "1",
            "ARM 3200 - Leadership and Ethics" to "2",
            "ARM 3202 - Applied Leadership Laboratory II" to "1",
            "ARM 3964 - Military Science Practicum" to "6",
            "ARM 4001 - Military Physical Training Laboratory 7" to "1",
            "ARM 4002 - Military Physical Training Laboratory 8" to "1",
            "ARM 4100 - Officership" to "2",
            "ARM 4101 - Advanced Leadership Laboratory I" to "0",
            "ARM 4200 - Leadership and Management" to "2",
            "ARM 4202 - Advanced Leadership Laboratory II" to "0",
            "ARM 4964 - Command Group Leadership" to "2",

            // Art History
            "AHT 2001 - Western Art History" to "3",
            "AHT 2002 - German Art History" to "3",

            // Biology
            "BIO 1110 - Cell Biology and Genetics" to "4",
            "BIO 1410 - Human Anatomy & Physiology I" to "5",
            "BIO 1420 - Human Anatomy & Physiology II" to "5",
            "BIO 2310 - Clinical Microbiology" to "4",
            "BIO 2320 - Cellular Microbiology" to "3",
            "BIO 2510 - Human Physiology I" to "3",
            "BIO 2520 - Human Physiology II" to "4",

            // Biomedical Engineering
            "BME 1010 - Introduction to Biomedical Engineering" to "2",
            "BME 2310 - Embedded Systems for Biomedical Engineers" to "3",
            "BME 2961 - Introduction to Human Body Systems for Radiological Applications" to "2",
            "BME 2963 - Fundamentals of Medical Imaging and Imaging AI" to "2",
            "BME 3010 - Medical Device Regulation and Standards" to "3",
            "BME 3210 - Medical Imaging Systems" to "3",
            "BME 3310 - Sensors, Actuators, and Interfaces" to "3",
            "BME 3410 - Biomechanics" to "4",
            "BME 3510 - Biotransport Phenomena" to "4",
            "BME 3610 - Biomaterials" to "3",
            "BME 3710 - Biomedical Instrumentation I" to "3",
            "BME 3980T - Topics in Biomedical Engineering: Integrated BME Lab Topics" to "2",
            "BME 4110 - Control Systems for Biomedical Applications" to "4",
            "BME 4980T - Topics in Biomedical Engineering: Medical Device Standards and Regulations" to "2",

            // Business
            "BUS 1850 - Information and Operations Technology" to "3",
            "BUS 2010 - Business Analysis and Data Storytelling" to "3",
            "BUS 2100 - Organizational Management" to "3",
            "BUS 2221 - Microeconomics" to "3",
            "BUS 2222 - Macroeconomics" to "3",
            "BUS 2225 - Health Care Economics" to "3",
            "BUS 2330 - Business Law" to "3",
            "BUS 2411 - Building Inclusive Teams" to "3",
            "BUS 2445 - Global Business" to "3",
            "BUS 2450 - Business Operations" to "3",
            "BUS 2510 - Principles of Financial Accounting" to "3",
            "BUS 2530 - Introduction to Finance" to "3",
            "BUS 2660 - Marketing" to "3",
            "BUS 2710 - Database Management" to "3",
            "BUS 2730 - Business Programming I" to "3",
            "BUS 2900 - Character in the Business Professions" to "3",
            "BUS 3010 - Business Analytics" to "3",
            "BUS 3200 - Principles of Economics and Financial Decision-Making" to "3",
            "BUS 3400 - Project Management" to "3",
            "BUS 3420 - Innovation and Entrepreneurship" to "3",
            "BUS 3445 - Leadership Communication" to "3",
            "BUS 3560 - Managerial Cost Accounting" to "3",
            "BUS 3580 - Intermediate Accounting I" to "3",
            "BUS 3585 - Intermediate Accounting II" to "3",
            "BUS 3593 - Intermediate Finance and Portfolio Theory" to "3",
            "BUS 3600 - Advanced Financial Analysis" to "3",
            "BUS 3650 - Branding and Brand Management" to "3",
            "BUS 3670 - Marketing Research" to "3",
            "BUS 3740 - Emerging Technology" to "3",
            "BUS 3790 - Web Design I" to "3",
            "BUS 3795 - Web Design II" to "3",
            "BUS 3800 - Continuous Improvement" to "3",
            "BUS 3805 - Lean-Six Sigma Techniques" to "3",
            "BUS 3820 - Planning, Scheduling, and Control" to "3",
            "BUS 3850 - Topics in Artificial Intelligence" to "3",
            "BUS 3890 - Supply Chain Management" to "3",
            "BUS 4310 - Legal Aspects of Innovation and Entrepreneurship" to "3",
            "BUS 4320 - Business Startups for Entrepreneurs" to "3",
            "BUS 4340 - Cultivating Your Entrepreneurial Mindset" to "3",
            "BUS 4490 - Human Resources" to "3",
            "BUS 4500 - Management Control Systems and Advanced Managerial Accounting" to "3",
            "BUS 4510 - Tax Planning and Research" to "3",
            "BUS 4530 - Personal Financial Planning" to "3",
            "BUS 4550 - Auditing and Advanced Accounting" to "3",
            "BUS 4560 - Accounting Ethics" to "3",
            "BUS 4570 - Accounting Information Systems" to "3",
            "BUS 4575 - Accounting Analytics and Artificial Intelligence" to "3",
            "BUS 4620 - Technical Selling" to "3",
            "BUS 4630 - Sales Process and Pipeline" to "3",
            "BUS 4640 - Sales Networking and Prospecting" to "3",
            "BUS 4660 - Digital Marketing" to "3",
            "BUS 4680 - Advertising and Promotion Strategies" to "3",
            "BUS 4690 - Consumer Behavior" to "3",
            "BUS 4801 - Business Internship" to "2",
            "BUS 4802 - Internship/Practicum" to "3",
            "BUS 4820 - Enterprise Resource Planning" to "3",
            "BUS 4900 - Forecasting and Strategy" to "3",
            "BUS 4901 - Business Capstone" to "3",
            "BUS 4950 - German Colloquium" to "3",

            // Biomolecular Engineering
            "BIE 1000 - Introduction to Chemical and Biomolecular Engineering" to "3",
            "BIE 2010 - Sophomore Seminar" to "1",
            "BIE 2100 - Principles and Applications of Biotechnology" to "3",
            "BIE 2300 - Informatics Computing" to "4",
            "BIE 2410 - Thermodynamics I" to "3",
            "BIE 2510 - Transport Phenomena I" to "3",
            "BIE 3100 - Cell Culture and Tissue Engineering" to "3",
            "BIE 3200 - Biopolymer and Nanomaterial Engineering" to "3",
            "BIE 3300 - Bioinformatics" to "4",
            "BIE 3400 - Kinetics and Bioreactor Design" to "3",
            "BIE 3420 - Thermodynamics II" to "3",
            "BIE 3500 - Unit Operations" to "3",
            "BIE 3520 - Transport Phenomena II" to "3",
            "BIE 3991 - Co-op Experience I" to "0",
            "BIE 3992 - Co-op Experience II" to "0",
            "BIE 4020 - Senior Seminar" to "1",
            "BIE 4100 - Synthetic Biology and Metabolic Engineering" to "3",
            "BIE 4200 - Engineering Controlled Drug Delivery and Nanomedicine" to "3",
            "BIE 4500 - Process Engineering Lab" to "3",
            "BIE 4600 - Bio Process Control" to "3",
            "BIE 4901 - Chemical and Biomolecular Engineering Senior Design I" to "3",
            "BIE 4902 - Chemical and Biomolecular Engineering Senior Design II" to "3",
            "BIE 4991 - Co-op Experience III" to "0",
            "BIE 4992 - Co-op Experience IV" to "0",

            // Chemistry
            "CHM 1010 - Chemistry I" to "4",
            "CHM 1010A - Chemistry I" to "4",
            "CHM 1020 - Chemistry II" to "4",
            "CHM 1050 - Chemistry for Life Sciences I" to "4",
            "CHM 1250 - Chemistry for Life Sciences II" to "4",
            "CHM 1310 - Chemistry of Food Molecules" to "4",
            "CHM 2210 - Organic Chemistry I" to "4",
            "CHM 2220 - Organic Chemistry II" to "3",
            "CHM 2225 - Organic Chemistry II Laboratory" to "2",
            "CHM 2310 - Biochemistry" to "4",
            "CHM 2980T - Topics in Chemistry: Quarter Chemistry III" to "2",
            "CHM 3510 - Advanced Analytical Chemistry" to "3",
            "CHM 3650 - Environmental Chemistry" to "3",
            "CHM 3710 - Polymer Chemistry" to "3",
            "CHM 3850 - Food Chemistry" to "3",

            // Civil + Arch Courses
            "CAE 1001 - Professional Growth I" to "0",
            "CAE 1811 - 1st Year Design" to "3",
            "CAE 1851 - Introduction to CAECM Graphics" to "2",
            "CAE 1871 - Materials and Methods" to "4",
            "CAE 1872 - Materials and Methods Laboratory" to "1",
            "CAE 2001 - Professional Growth II" to "0",
            "CAE 2411 - Thermal Sciences" to "3",
            "CAE 2511 - Statics" to "3",
            "CAE 2512 - Mechanics of Materials" to "3",
            "CAE 2711 - Fluid Mechanics" to "3",
            "CAE 2980T - Topics in Civil and Architectural Engineering: Building Construction Methods Transition" to "2",
            "CAE 3001 - Professional Growth III" to "0",
            "CAE 3501 - Principles of Structural Engineering" to "3",
            "CAE 3511 - Analysis of Structures" to "3",
            "CAE 3521 - Design of Reinforced Concrete Structures" to "3",
            "CAE 3561 - Design of Steel Structures" to "3",
            "CAE 3861 - Specifications and the Project Manual" to "2",
            "CAE 3891 - Introduction to Disaster Relief and Global Sustainable Development" to "3",
            "CAE 3991 - Co-op Experience I" to "0",
            "CAE 3992 - Co-op Experience II" to "0",
            "CAE 4811 - Real Estate Development Economics" to "3",
            "CAE 4861 - Construction Law and Contracts" to "3",
            "CAE 4881 - Sustainability and Resilience" to "3",
            "CAE 4901 - Architectural Engineering and Construction Management Capstone I" to "4",
            "CAE 4902 - Architectural Engineering and Construction Management Capstone II" to "4",
            "CAE 4991 - Co-op Experience III" to "0",
            "CAE 4992 - Co-op Experience IV" to "0",

            // Civil Engineering Courses
            "CVE 2851 - Introduction to Civil 3D" to "2",
            "CVE 2852 - Introduction to Geographic Information Systems (GIS)" to "2",
            "CVE 3201 - Principles of Environmental Engineering" to "3",
            "CVE 3251 - Design of Municipal Potable Water and Wastewater Treatment Plants" to "3",
            "CVE 3301 - Principles of Soils and Geotechnical Engineering" to "3",
            "CVE 3601 - Principles of Transportation Engineering" to "3",
            "CVE 3611 - Traffic Engineering" to "3",
            "CVE 3661 - Geometric Design of Roadways" to "3",
            "CVE 3701 - Principles of Water Resources Engineering" to "3",
            "CVE 3721 - Analysis and Design of Potable Water Distribution Systems and Wastewater Collection Systems" to "3",
            "CVE 3741 - Design of Stormwater Management Systems" to "3",
            "CVE 3811 - Principles of Site Development" to "3",
            "CVE 4901 - Civil Engineering Capstone I" to "4",
            "CVE 4902 - Civil Engineering Capstone II" to "4",

            // Communications Courses
            "COM 1001 - College Writing" to "3",
            "COM 2001 - Writing for the STEM Disciplines" to "3",
            "COM 3001 - Professional Presentations" to "3",

            // Computer Engineering Courses
            "CPE 1500 - Digital Logic" to "4",
            "CPE 1510 - Computer Architecture and Assembly Language" to "4",
            "CPE 2600 - Systems Programming" to "4",
            "CPE 2610 - Embedded Systems" to "4",
            "CPE 3300 - Computer Networking" to "4",
            "CPE 3600 - Advanced Embedded Systems" to "4",
            "CPE 4510 - Superscalar, Multicore, and Multiprocessor Architecture" to "3",
            "CPE 4520 - Memory System and I/O System Architecture" to "3",
            "CPE 4610 - Embedded Systems Fabrication" to "3",
            "CPE 4800 - Information Security" to "4",
            "CPE 4901 - Computer Engineering Senior Design Project I" to "3",
            "CPE 4902 - Computer Engineering Senior Design Project II" to "3",

            // Computer Science Courses
            "CSC 1110 - Software Development" to "4",
            "CSC 1110A - Software Development" to "4",
            "CSC 1120 - Data Structures and Graphical Interfaces" to "4",
            "CSC 1120A - Data Structures and Graphical Interfaces" to "4",
            "CSC 2210 - Procedural and Object-Oriented C++" to "4",
            "CSC 2611 - AI Tools" to "3",
            "CSC 1310 - Introduction to Programming with Python" to "1",
            "CSC 2661 - Python for AI" to "1",
            "CSC 2663 - Machine Learning Techniques" to "1",
            "CSC 2621 - Data Science" to "3",
            "CSC 3210 - Operating Systems" to "3",
            "CSC 3310 - Algorithms and Advanced Data Structures" to "3",
            "CSC 3320 - Databases" to "3",
            "CSC 3511 - Security and Networking" to "3",
            "CSC 4201 - Microservices and Cloud Computing" to "3",
            "CSC 4241 - GPU Programming" to "3",
            "CSC 4243 - Compiler Construction" to "3",
            "CSC 4341 - Competitive Programming" to "3",
            "CSC 4601 - Theory of Machine Learning" to "3",
            "CSC 4611 - Introduction to Deep Learning" to "3",
            "CSC 4631 - Artificial Intelligence" to "3",
            "CSC 4641 - Natural Language Processing" to "3",
            "CSC 4651 - Deep Learning in Signal Processing" to "3",
            "CSC 4801 - Data Science Practicum" to "3",
            "CSC 4901 - Computer Science Capstone I" to "3",
            "CSC 4902 - Computer Science Capstone II" to "3",
            "CSC 4911 - Mobile Application Development" to "3",
            "CSC 4941 - Robotics" to "3",

            // CM Classes
            "CON 2001 - Introduction to Construction Management" to "3",
            "CON 2011 - Surveying" to "2",
            "CON 2071 - Construction Safety" to "2",
            "CON 2980 - Topics in Construction Management" to "3",
            "CON 3001 - Principles of Construction Project Management" to "3",
            "CON 3011 - Building Mechanical and Electrical Systems for CM" to "3",
            "CON 3021 - Construction Estimating" to "3",
            "CON 3061 - Construction Scheduling" to "3",
            "CON 3071 - Construction Jobsite and Equipment Management" to "3",
            "CON 4021 - Construction Finance and Accounting" to "3",
            "CON 4051 - Construction Project Management II" to "3",
            "CON 4901 - Construction Management Capstone I" to "4",
            "CON 4902 - Construction Management Capstone II" to "4",

            // CSE Courses
            "CSE 3991 - Co-op Experience I" to "0",
            "CSE 3992 - Co-op Experience II" to "0",
            "CSE 4200 - Engineering Applications of MATLAB" to "3",
            "CSE 4991 - Co-op Experience III" to "0",
            "CSE 4992 - Co-op Experience IV" to "0",

            // Electrical Engineering Courses
            "ELE 1000 - Introduction to Electrical Engineering" to "3",
            "ELE 1601 - Introduction to Programming for EEs" to "3",
            "ELE 1801 - Transfer Digital Logic and Embedded Systems" to "3",
            "ELE 2001 - Electric Circuits I: Theory and Applications" to "4",
            "ELE 2011 - Electric Circuits II: Theory and Applications" to "4",
            "ELE 2051 - Circuit Theory for Mechanical Engineering" to "3",
            "ELE 2610 - Embedded Systems" to "4",
            "ELE 2801 - Bridge Digital Design and Procedural Programming" to "3",
            "ELE 3101 - Electronics I" to "4",
            "ELE 3111 - Electronics II" to "3",
            "ELE 3141 - Transfer Electronics" to "3",
            "ELE 3151 - Bridge Electronics II" to "3",
            "ELE 3201 - Electromagnetics and Transmission Lines" to "4",
            "ELE 3300 - Signals and Systems" to "3",
            "ELE 3310 - Introduction to Probability and Random Processes" to "3",
            "ELE 3320 - Digital Signal Processing" to "3",
            "ELE 3401 - Electric Power and Machines" to "4",
            "ELE 3510 - Digital Systems" to "4",
            "ELE 3701 - Control Systems" to "4",
            "ELE 3900 - Career and Professional Guidance" to "1",
            "ELE 4142 - Modern Electronic Systems" to "3",
            "ELE 4190 - THL Advanced Analog Design" to "3",
            "ELE 4240 - Advanced Electromagnetics and Antenna Theory" to "4",
            "ELE 4290 - THL Radio Frequencies" to "3",
            "ELE 4291 - THL Microwaves" to "3",
            "ELE 4300 - Principles of Communications" to "3",
            "ELE 4320 - Applications of DSP" to "3",
            "ELE 4390 - THL Communication Network" to "3",
            "ELE 4403 - Specialty Electric Machines" to "3",
            "ELE 4440 - Power Electronics" to "3",
            "ELE 4447 - Power System Models and Analysis" to "3",
            "ELE 4451 - Grid Stability" to "3",
            "ELE 4480 - Electrical Power Systems Quality" to "3",
            "ELE 4610 - Advanced Programming for EEs" to "3",
            "ELE 4630 - Advanced Embedded Systems" to "3",
            "ELE 4701 - Control Systems Applications" to "3",
            "ELE 4901 - Electrical Engineering - Senior Design Project I" to "3",
            "ELE 4902 - Electrical Engineering - Senior Design Project II" to "3",
            "ELE 4940 - THL Bachelor Thesis" to "3",

            // English for Academic Purposes
            "EAP 0100 - Intensive Grammar Application" to "3",
            "EAP 0200 - Critical Reading and Listening" to "3",

            // Fine Arts Courses
            "FNA 2002 - Drama and The Theater" to "3",
            "FNA 3001 - Creative Writing" to "3",
            "FNA 4010 - Film and Media Studies" to "3",

            // General Engineering Courses
            "EGR 2961 - General AI Application Foundation" to "1",
            "EGR 2963 - General AI Application Contexts" to "1",
            "EGR 4801 - AI for Emerging Applications Practicum" to "3",

            // German Courses
            "GER 1001 - Elementary German" to "3",
            "GER 2001 - Intermediate German" to "3",
            "GER 3001 - Advanced German" to "3",

            // History Courses
            "HST 1013 - United States History I" to "3",
            "HST 1014 - United States History II" to "3",
            "HST 1015 - Latin American History I" to "3",
            "HST 1016 - Latin American History II" to "3",
            "HST 2011 - American Revolution" to "3",
            "HST 2012 - Civil War and Reconstruction" to "3",
            "HST 2014 - History of US World’s Fairs" to "3",
            "HST 2015 - Topics in Twentieth Century American History" to "3",
            "HST 2021 - Topics in Modern European History" to "3",
            "HST 2022 - German History" to "3",
            "HST 2031 - World War II" to "3",
            "HST 2041 - Cuban History" to "3",
            "HST 2053 - Music History" to "3",

            // Honors Courses
            "HON 2011 - Honors Practicum" to "2",
            "HON 2051 - Honors Seminar I" to "3",
            "HON 2052 - Honors Seminar II" to "3",
            "HON 2060 - Honors Travel Experience" to "0",
            "HON 3060 - Honors Research/Entrepreneur Experience" to "0",
            "HON 4060 - Honors Senior Reflection" to "0",

            // Humanities Courses
            "HUM 1001 - THL Humanities I" to "3",
            "HUM 2001 - THL Humanities II" to "3",

            // Industrial Engineering Courses
            "IND 1000 - Introduction to Industrial Engineering" to "1",
            "IND 2010 - Logic Development and Computer Programming for Engineers" to "3",
            "IND 2030 - Applied Statistics for Industrial Engineers" to "3",
            "IND 2700 - Engineering Economics" to "3",
            "IND 3210 - Automation Technologies" to "4",
            "IND 3400 - Quality Systems" to "3",
            "IND 3410 - Design of Experiments and Data Analysis for Engineers" to "3",
            "IND 3510 - Fundamentals of Enterprise Operations for Engineers" to "3",
            "IND 3600 - Ergonomics and Work Methods" to "4",
            "IND 3700 - Project Management for Systems Change" to "3",
            "IND 3810 - Process Modelling and Optimization" to "3",
            "IND 3820 - Stochastic Processes" to "3",
            "IND 4110 - Research Methods" to "3",
            "IND 4120 - Healthcare Systems Engineering" to "3",
            "IND 4210 - Computer-Aided Manufacturing/CNC Machining/Additive Manufacturing" to "3",
            "IND 4310 - Production Planning and Inventory Control" to "3",
            "IND 4320 - Facilities Design" to "3",
            "IND 4330 - Modern Manufacturing Processes" to "3",
            "IND 4410 - Six Sigma for Engineers" to "3",
            "IND 4430 - Lean Manufacturing Enterprise for Engineers" to "3",
            "IND 4610 - Safety Systems Engineering" to "3",
            "IND 4621 - Sociotechnical Systems Engineering" to "3",
            "IND 4622 - Organization and Job Design" to "3",
            "IND 4630 - Product Design and Development Processes" to "3",
            "IND 4710 - Financial Engineering" to "3",
            "IND 4720 - Supply Chain Engineering" to "3",
            "IND 4830 - Process Simulation" to "3",
            "IND 4840 - Advanced Simulation" to "3",
            "IND 4901 - Industrial Engineering Senior Design Capstone I" to "3",
            "IND 4902 - Industrial Engineering Senior Design Capstone II" to "3",


            // Interdisciplinary Courses
            "IDS 2020 - Career Development" to "0",
            "IDS 3901 - Interdisciplinary Design" to "3",

            // Literature Courses
            "LIT 1010 - American Literature I" to "3",
            "LIT 1020 - American Literature II" to "3",
            "LIT 2001 - Science Fiction" to "3",
            "LIT 2010 - Literary Genres" to "3",
            "LIT 2020 - Contemporary Literature" to "3",

            // Mathematics Courses
            "MTH 1030 - Quantitative Reasoning for Health Care Professionals" to "2",
            "MTH 1050 - Finite Mathematics" to "4",
            "MTH 1080 - Precalculus Mathematics" to "4",
            "MTH 1080A - Precalculus Mathematics" to "4",
            "MTH 1110 - Calculus I" to "4",
            "MTH 1110A - Calculus I" to "4",
            "MTH 1120 - Calculus II" to "4",
            "MTH 1840 - Computer Applications in Actuarial Science" to "2",
            "MTH 2130 - Calculus III" to "4",
            "MTH 2140 - Differential Equations" to "3",
            "MTH 2310 - Discrete Mathematics" to "3",
            "MTH 2340 - Linear Algebra with Applications" to "3",
            "MTH 2410 - Statistics for Actuarial Science" to "3",
            "MTH 2430 - Statistical Methods for Health Care" to "3",
            "MTH 2450 - Business Statistics and Analytics" to "4",
            "MTH 2480 - Probability and Statistics" to "3",
            "MTH 2610 - Probability for Actuarial Science I" to "4",
            "MTH 2620 - Probability for Actuarial Science II" to "4",
            "MTH 2680 - Introduction to Probability" to "4",
            "MTH 2980T - Topics in Mathematics: Quarter Calculus III" to "3",
            "MTH 2980U - Topics in Mathematics: Quarter Calculus III and IV" to "5",
            "MTH 3340 - Abstract Algebra with Applications" to "3",
            "MTH 3410 - Applied Regression Analysis" to "3",
            "MTH 3999 - Mathematics Independent Study" to "3",
            "MTH 4130 - Complex Analysis" to "3",
            "MTH 4150 - Partial Differential Equations" to "3",

            // Mechanical Engineering Courses
            "MEC 1602 - Introduction to Solid Modeling and Design" to "3",
            "MEC 1900 - Introduction to Mechanical Engineering" to "1",
            "MEC 1910 - Computer Applications in Engineering" to "3",
            "MEC 2010 - Engineering Mechanics I: Statics" to "3",
            "MEC 2020 - Engineering Mechanics II: Dynamics" to "3",
            "MEC 2030 - Mechanics of Materials" to "4",
            "MEC 2110 - Thermodynamics I" to "3",
            "MEC 2501 - Statics and Mechanics of Materials" to "4",
            "MEC 3000 - THL Modeling and Numerical Analysis Transfer" to "3",
            "MEC 3040 - Computer-Aided Design of Machines" to "3",
            "MEC 3060 - Design of Machine Components" to "3",
            "MEC 3120 - Fluid Mechanics" to "3",
            "MEC 3130 - Heat Transfer" to "3",
            "MEC 3140 - Thermodynamics II" to "3",
            "MEC 3210 - Material Science" to "3",
            "MEC 3220 - Materials and Manufacturing Processes" to "3",
            "MEC 3310 - Instrumentation and Measurements" to "3",
            "MEC 3320 - Dynamic Systems" to "3",
            "MEC 3991 - Co-op Experience I" to "0",
            "MEC 3992 - Co-op Experience II" to "0",
            "MEC 4060 - Finite Element Analysis" to "3",
            "MEC 4160 - Computational Fluid Dynamics" to "3",
            "MEC 4270 - Fatigue and Fracture in Mechanical Design" to "3",
            "MEC 4310 - Automatic Control Systems" to "3",
            "MEC 4350 - Mechanical System Simulation" to "3",
            "MEC 4470 - Introduction to Robotics" to "3",
            "MEC 4670 - Experimental Stress Analysis" to "3",
            "MEC 4671 - Vibration Control" to "3",
            "MEC 4672 - Applications in Finite Element Modeling" to "3",
            "MEC 4673 - Advanced Machine Design" to "3",
            "MEC 4674 - Medical Applications in Mechanical Engineering" to "3",
            "MEC 4675 - Vehicle Dynamics" to "3",
            "MEC 4676 - Composite Materials" to "3",
            "MEC 4677 - Applied Numerical Methods" to "3",
            "MEC 4678 - Data and Mechanical Engineering" to "3",
            "MEC 4770 - Fluid Power Systems" to "3",
            "MEC 4810 - Thermo-Fluid Systems Lab" to "3",
            "MEC 4870 - HVAC Systems Design" to "3",
            "MEC 4871 - Aerodynamics" to "3",
            "MEC 4872 - Compressible Flow" to "3",
            "MEC 4873 - Gas Turbines and Aircraft Engines" to "3",
            "MEC 4874 - Renewable and Sustainable Energy Systems" to "3",
            "MEC 4875 - Internal Combustion Engines" to "3",
            "MEC 4901 - Mechanical Engineering Capstone Design I" to "3",
            "MEC 4902 - Mechanical Engineering Capstone Design II" to "3",
            "MEC 4950 - THL Bachelor’s Thesis" to "3",
            "MEC 4980 - Topics in Mechanical Engineering" to "3",
            "MEC 4991 - Co-op Experience III" to "0",
            "MEC 4992 - Co-op Experience IV" to "0",

            // Music Courses
            "MUS 0100 - University Orchestra (not for credit)" to "0",
            "MUS 0200 - Jazz Ensemble (not for credit)" to "0",
            "MUS 0300 - Concert Band (not for credit)" to "0",
            "MUS 0400 - Concert Choir (not for credit)" to "0",
            "MUS 0500 - Pep Band (not for credit)" to "0",
            "MUS 0600 - Jazz Combo" to "0",
            "MUS 0700 - Electronic Orchestra" to "0",
            "MUS 1100 - University Orchestra (for credit)" to "1",
            "MUS 1200 - Jazz Ensemble (for credit)" to "1",
            "MUS 1300 - Concert Band (for credit)" to "1",
            "MUS 1400 - Concert Choir (for credit)" to "1",
            "MUS 1500 - Pep Band (for credit)" to "1",

            // Naval Science
            "NAV 1001 - Drill and Information Briefing" to "0",
            "NAV 1009 - Introduction to Naval Science" to "2",
            "NAV 1022 - Sea Power and Maritime Affairs" to "3",
            "NAV 2151 - Navigation" to "3",
            "NAV 2185 - Leadership and Management" to "3",
            "NAV 3142 - Naval Ship Systems 1" to "3",
            "NAV 3161 - Evolution of the Art of War" to "3",
            "NAV 3162 - Naval Ship Systems 2" to "3",
            "NAV 3191 - Fundamentals of Maneuver Warfare" to "3",
            "NAV 3964 - Practicum in U.S. Marine Corps Leadership and Management" to "3",
            "NAV 4152 - Naval Operations and Seamanship" to "3",
            "NAV 4186 - Leadership and Core-Value-Based Decision-Making" to "4",

            // Nursing Courses
            "NUR 1000 - Introduction to Professional Nursing Practice" to "3",
            "NUR 2000 - Nutrition in Health and Illness Across the Life Span" to "2",
            "NUR 2001 - Pathophysiology and Pharmacology I" to "5",
            "NUR 2002 - Pathophysiology and Pharmacology II" to "4",
            "NUR 2003 - Pathophysiology (ASD)" to "5",
            "NUR 2004 - Pharmacology (ASD)" to "4",
            "NUR 2010 - Health Assessment" to "4",
            "NUR 2015 - Health Assessment and Foundations of Safe, Person-Centered Nursing Care (ASD)" to "5",
            "NUR 2020 - Foundations of Safe, Person-Centered Nursing Care" to "6",
            "NUR 2500 - Global Health Care and International Health Care Systems" to "3",
            "NUR 3000 - Transcultural and Family Dynamics in Healthcare (PBEL)" to "3",
            "NUR 3001 - Transcultural Dynamics in Healthcare (PBEL) (ASD)" to "2",
            "NUR 3005 - Nursing Care of Older Adults" to "3",
            "NUR 3006 - Gerontological Management of Care" to "3",
            "NUR 3010 - Episodic Health Challenges" to "7",
            "NUR 3011 - Acquisition of Psychomotor Skills and Integration of Clinical Reasoning I" to "1",
            "NUR 3015 - Episodic and Restorative Health Care (ASD)" to "7",
            "NUR 3016 - Acquisition of Psychomotor Skills and Integration of Clinical Reasoning (ASD)" to "2",
            "NUR 3020 - Chronic Health Challenges" to "5",
            "NUR 3021 - Acquisition of Psychomotor Skills and Integration of Clinical Reasoning II" to "1",
            "NUR 3030 - Population Health (PBEL)" to "5",
            "NUR 3100 - Principles of Electrocardiograph (ECG) Interpretation and Monitoring" to "2",
            "NUR 3320 - Complementary and Integrative Health Therapies" to "2",
            "NUR 3950 - Interprofessional Education (IPE)" to "0",
            "NUR 4001 - Preparing for NCLEX Licensure Success" to "2",
            "NUR 4010 - Supportive Care for End-of-Life, Mental Health, and Trauma-Informed Care" to "5",
            "NUR 4015 - Chronic Health Challenges (ASD)" to "7",
            "NUR 4020 - Complex High Acuity Health Challenges" to "5",
            "NUR 4030 - Practice Synthesis: Preceptorship and Simulations" to "4",
            "NUR 4901 - Nursing Research and Evidence-Based Practice (PBEL)" to "3",
            "NUR 4902 - Nurses as Leaders in Advancing Health Care (PBEL)" to "3",
            "NUR 4903 - Nursing Research and Evidence-Based Practice (Part I)" to "2",
            "NUR 4904 - Nursing Research and Evidence-Based Practice (Part II)" to "1",

            // Philosophy Courses
            "PHL 3101 - Ethics for Professional Managers and Engineers" to "3",
            "PHL 3102 - Ethics of Digital Technologies and Artificial Intelligence" to "3",
            "PHL 3103 - Bioethics" to "3",
            "PHL 3104 - Eastern Philosophy" to "3",
            "PHL 3201 - Introduction to Philosophy" to "3",
            "PHL 3202 - Introduction to Logic" to "3",
            "PHL 3203 - Epistemology" to "3",
            "PHL 3204 - Metaphysics" to "3",
            "PHL 3205 - Minds, Brains, and Computers" to "3",
            "PHL 3206 - Social and Political Philosophy" to "3",
            "PHL 3207 - Philosophy of Science" to "3",
            "PHL 3208 - Philosophy of Art" to "3",

            // Physics Courses
            "PHY 1110 - Physics I - Mechanics and Thermodynamics" to "4",
            "PHY 1110A - Physics I - Mechanics and Thermodynamics" to "4",
            "PHY 1120 - Physics II - Electricity, Magnetism, and Optics" to "4",
            "PHY 1980T - Topics in Physics: Waves, Relativity, Thermo Transition" to "1.33",
            "PHY 2600 - Introduction to Optics and Photonics" to "3",
            "PHY 3530 - Quantum and Modern Physics" to "3",
            "PHY 3550 - Nuclear Physics" to "3",
            "PHY 3600 - Lasers and Applications" to "3",
            "PHY 3700 - Physics of Electronic Materials and Semiconductor Devices" to "4",
            "PHY 3810 - Introduction to Biophysics" to "3",
            "PHY 3910 - Astronomy and Astrophysics" to "3",


            // Political Science
            "PSC 2010 - Foundations of Political Science" to "3",
            "PSC 2011 - American Government" to "3",
            "PSC 2015 - International Relations" to "3",
            "PSC 2016 - Urban Studies" to "3",

            // Psychology
            "PSY 1001 - Foundations of Psychology" to "3",
            "PSY 2002 - Psychology of Design" to "3",
            "PSY 2003 - Organizational Psychology" to "3",
            "PSY 2005 - The Family: Psychological and Social Perspectives" to "3",
            "PSY 2006 - Death, Dying, and Grief" to "3",
            "PSY 2007 - Addictive and Compulsive Behavior" to "3",
            "PSY 2010 - Understanding Human Language" to "3",
            "PSY 2980 - Topics in Psychology" to "3",
            "PSY 2999 - Psychology Independent Study" to "3",
            "PSY 3001 - Cognitive Psychology" to "3",
            "PSY 3002 - Psychological Disorders and Mental Health" to "3",
            "PSY 3003 - Developmental Psychology" to "3",
            "PSY 3004 - Social Psychology" to "3",

            // Raider Success
            "RSC 0100 - Strategies for International Student Success" to "1",
            "RSC 0101 - Foundations of Student Success" to "1",
            "RSC 0102 - Academic Coaching and Support" to "0",
            "RSC 0103 - Perspective, Potential, and Purpose" to "1",
            "RSC 0104 - Mind, Mood, and Movement" to "1",
            "RSC 1010 - First-Year Seminar I" to "1",
            "RSC 1011 - First-Year Seminar II" to "1",
            "RSC 2010 - Second-Year Seminar I" to "1",
            "RSC 2011 - Second-Year Seminar II" to "1",
            "RSC 3010 - Third-Year Seminar I" to "1",
            "RSC 3011 - Third-Year Seminar II" to "1",
            "RSC 4010 - Fourth-Year Seminar I" to "1",
            "RSC 4011 - Fourth-Year Seminar II" to "1",

            // Science
            "SCI 1610 - Environmental Science" to "4",
            "SCI 2000 - Sound and Light" to "3",
            "SCI 2410 - Limnology: The Science of Inland Waters" to "3",
            "SCI 3010 - Structure and Properties of Modern Materials" to "3",
            "SCI 3610 - Science of Climate Change" to "3",
            "SCI 3700 - Physical Geology" to "3",
            "SCI 3750 - Nanoscience and Nanotechnology" to "3",

            // Socielogy
            "SOC 1001 - Foundations of Sociology" to "3",
            "SOC 3001 - Cybercrime: Human Perspectives" to "3",
            "SOC 4001 - Digital Society" to "3",

            // Software Engineering
            "SWE 2410 - Design and Cloud Patterns" to "3",
            "SWE 2511 - Web Applications" to "3",
            "SWE 2710 - Software Tools and Process" to "3",
            "SWE 2721 - Introduction to Software Verification" to "3",
            "SWE 3411 - Software Requirements and Architecture" to "4",
            "SWE 3710 - Software Development Laboratory I" to "3",
            "SWE 3720 - Software Development Laboratory II" to "3",
            "SWE 4211 - Real-time Systems" to "3",
            "SWE 4411 - Game Development" to "3",
            "SWE 4511 - DevSecOps" to "4",
            "SWE 4540 - Network Security Tools and Practices" to "4",
            "SWE 4901 - Software Engineering Capstone I" to "3",
            "SWE 4902 - Software Engineering Capstone II" to "3",

            // Spanish
            "SPN 1001 - Elementary Spanish" to "3",
            "SPN 2001 - Intermediate Spanish" to "3",
            "SPN 3001 - Advanced Spanish" to "3",
            "SPN 3980 - Topics in the Spanish-Speaking World" to "3",

            // Tech Com
            "TCM 1010 - Argument and Persuasion" to "3",
            "TCM 1020 - Writing for Digital Media" to "3",
            "TCM 2010 - Interpersonal Communication" to "3",
            "TCM 2020 - Communication Dynamics of High-Performance Teams" to "3",
            "TCM 2050 - Health Care Communication" to "3",
            "TCM 2060 - Communication Graphics for Professionals" to "3",
            "TCM 2980 - Topics in Technical Communication" to "3",
            "TCM 3010 - Digital Storytelling" to "3",
            "TCM 3020 - Advanced Presentations" to "3",
            "TCM 3030 - e-Learning Development" to "3",
            "TCM 3110 - Project Communications" to "3",
            "TCM 3210 - User Documentation" to "3",
            "TCM 3801 - Technical Communication Internship" to "3",

            // Undergrad Research
            "UGR 4971 - Undergraduate Research Thesis I" to "3",
            "UGR 4972 - Undergraduate Research Thesis II" to "3",

            // User Experience
            "UXD 1001 - Human-Centered Design" to "3",
            "UXD 1020 - Visual Design" to "3",
            "UXD 1030 - Interface Design" to "3",
            "UXD 1040 - Design Thinking" to "3",
            "UXD 2010 - Inclusive Design" to "3",
            "UXD 2020 - Interaction Design" to "3",
            "UXD 2030 - Designing for Extended Reality" to "3",
            "UXD 2040 - People + Automation" to "3",
            "UXD 2050 - UX Writing" to "3",
            "UXD 2961 - Human-centered AI" to "1",
            "UXD 2963 - Intelligent User Interfaces" to "1",
            "UXD 3010 - UX Research" to "3",
            "UXD 3020 - Design for Chat and Voice" to "3",
            "UXD 3030 - Data Visualization" to "3",
            "UXD 3040 - Agile Project Management" to "3",
            "UXD 3050 - Search Engine Optimization" to "3",
            "UXD 3060 - Professional Portfolio" to "3",
            "UXD 4020 - UX of Physical Products" to "3",
            "UXD 4030 - UX Strategy" to "3",
            "UXD 4040 - UX in Transportation" to "3",
            "UXD 4060 - UX in Healthcare" to "3",
            "UXD 4901 - UX Senior Design" to "3"
        )

        fun getCourseCreditMap(): Map<String, String> {
            return courseCreditMap
        }
    }
}